spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:1000}
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
  flyway:
    enabled: false
  profiles:
    group:
      test: test
      local: local
      prod: prod

---

spring:
  config:
    activate:
      on-profile: test

  h2:
    console.enabled: true
    console.path: /h2-console

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem://localhost/~/goodgame;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connectionTimeout: 3000
      max-lifetime: 58000  # 58s
      maximumPoolSize: 10
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
      auto-commit: false

---

spring:
  config:
    activate:
      on-profile: local

  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mariadb://localhost:13306/goodgame?useSSL=false
      username: root
      password: root
      connectionTimeout: 3000
      max-lifetime: 58000  # 58s
      maximumPoolSize: 10
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
      auto-commit: false
