version: "3"

services:
  maria:
    image: mariadb:10.4
    container_name: goodgame-marida-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goodgame
      TZ: Asia/Seoul
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/log:/var/log/maria
      - ./mariadb/conf:/etc/mysql/conf.d
