spring:
  config:
    import:
      - persistence-jpa.yml
      - security.yml
  profiles:
    active: test-local
---
spring:
  config:
    activate:
      on-profile: test

authentication:
  enabled: true
  url-patterns:
    - "/api/v1/**"


---
spring:
  config:
    activate:
      on-profile: test-local

authentication:
  enabled: true
  url-patterns:
    - "/api/v1/**"

---
spring:
  config:
    activate:
      on-profile: docker-local

authentication:
  enabled: true
  url-patterns:
    - "/api/v1/**"
---
spring:
  config:
    activate:
      on-profile: prod

authentication:
  enabled: true
  url-patterns:
    - "/api/v1/**"
